[project]
name = "patent-text2cypher-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.4.0",
    "google-generativeai>=0.8.6",
    "neo4j>=6.2.0",
    "neo4j-graphrag[openai]>=1.16.0",
    "openai>=1.109.1",
    "python-dotenv>=1.2.2",
]
